# TOML format v0.5.0.
# https://github.com/toml-lang/toml

modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)

issueTrackerURL="https://github.com/dkoeplin/meeples/issues"
displayURL="https://github.com/dkoeplin/meeples"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="meeples"
version="1.0"
displayName="Meeples" #mandatory
logoFile="examplemod.png" #optional
credits=""
authors="ironclad49er"
description='''
Meeples!
'''

# Forge 28
[[dependencies.meeples]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE" # BEFORE or AFTER
    side="BOTH"     # BOTH, CLIENT or SERVER

# Minecraft 1.14.4
[[dependencies.meeples]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
